# Site settings
title_left    : "Rishi "
title_right   : "Giri 🍁" # default: ""
description   : "0.1x Programmer"
keywords      : "Rishi, Rishi Giri, Giri, iama_rishi, CodeDotJS, DotJS, Rishi-Giri-1, Rishi_Giri_, JavaScript Developer, Programmer"
url           : "https://ir8x.me" # site url
baseurl       : "" # apply repo name like "/myproject" if used under gh-pages branch, else (under master branch) just leave empty/blank
cover         : "https://images.unsplash.com/photo-1497412159286-98933a0e327f?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1319&q=80" # image uri like logo/cover image for site seo

google_analytics  : UA-125012328-1
twitter_username  : "Rishi_Giri_"
comments_enabled  : true # if enabled (set to true), please provide your disqus_username
disqus_shortname  : "rishi-giri"
postshare_enabled : false

# Build settings
permalink   : /:year/:title/
markdown    : kramdown
highlighter : rouge

source      : ./
destination : ./_site

# Sass configuration
sass:
  sass_dir  : assets/scss
  style     : compressed # expanded

# Author settings
author:
  name     : "Rishi Giri"

plugins:
  - jekyll-sitemap
  - bourbon
  - jekyll-paginate

# navbar pages
navbar:
  - slug : about
    title: About
  - slug : blog
    title: Blog
  - slug : projects
    title: Projects
  - slug : resume
    title: Resume

include: ['work', 'arena', 'weblogs']

exclude: ["gulp", "node_modules", "bower", "bower_components", "config.rb", "src", "Gemfile", "Gemfile.lock", ".rvmrc", ".rbenv-version", "package.json", "gulpfile.js", "README.md", "Rakefile", "changelog.md", "script", "v2", "archive"]

collections:
  notes:
    output: true

